name: Jira Sync

on:
  issues:
    types: [opened, edited, labeled, unlabeled]
  issue_comment:
    types: [created]

jobs:
  sync:
    name: Sync Items
    runs-on: ubuntu-latest
    steps:
      - name: Sync Github Issues to Jira
        uses: jordansilva/github-action-issue-to-jira@v1.1.2
        with:
          jiraHost: ${{ secrets.JIRA_HOST }}
          jiraUsername: ${{ secrets.JIRA_USERNAME }}
          jiraPassword: ${{ secrets.JIRA_PASSWORD }}
          project: KANBAN
          assignee: ""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
