name: 🔷 Sync to Jira

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to be performed'
        required: true
        default: 'mirror-issues'
      issue-numbers:
        description: 'Issue numbers to sync (comma-separated)'
        required: true

jobs:
  sync-to-jira:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      JIRA_URL: ${{ secrets.JIRA_URL }}
      JIRA_USER: ${{ secrets.JIRA_USERNAME }}
      JIRA_PASS: ${{ secrets.JIRA_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Sync to Jira
        uses: espressif/sync-jira-actions@v1
        with:
          jira-project: KANBAN
          jira-component: GitHub
          jira-issue-type: Task
          action: ${{ github.event.inputs.action }}
          issue-numbers: ${{ github.event.inputs.issue-numbers }}
